#include<stdio.h>
#include<conio.h>

int main()
{
    int i;
    clrscr();
    for(i=0;i<=255;i++)
        printf("ASCII value of character %c is %d\n", i, i);
    getch();
    return 0;
}

/*
O/P:
ASCII value of character   is 0
ASCII value of character ☺ is 1
ASCII value of character ☻ is 2
ASCII value of character ♥ is 3
ASCII value of character ♦ is 4
ASCII value of character ♣ is 5
ASCII value of character ♠ is 6
ASCII value of character  is 7
ASCII value of character is 8
ASCII value of character         is 9
ASCII value of character
 is 10
ASCII value of character ♂ is 11
ASCII value of character ♀ is 12
 is 13 of character
ASCII value of character ♫ is 14
ASCII value of character ☼ is 15
ASCII value of character ► is 16
ASCII value of character ◄ is 17
ASCII value of character ↕ is 18
ASCII value of character ‼ is 19
ASCII value of character ¶ is 20
ASCII value of character § is 21
ASCII value of character ▬ is 22
ASCII value of character ↨ is 23
ASCII value of character ↑ is 24
ASCII value of character ↓ is 25
ASCII value of character → is 26
ASCII value of character ← is 27
ASCII value of character ∟ is 28
ASCII value of character ↔ is 29
ASCII value of character ▲ is 30
ASCII value of character ▼ is 31
ASCII value of character   is 32
ASCII value of character ! is 33
ASCII value of character " is 34
ASCII value of character # is 35
ASCII value of character $ is 36
ASCII value of character % is 37
ASCII value of character & is 38
ASCII value of character ' is 39
ASCII value of character ( is 40
ASCII value of character ) is 41
ASCII value of character * is 42
ASCII value of character + is 43
ASCII value of character , is 44
ASCII value of character - is 45
ASCII value of character . is 46
ASCII value of character / is 47
ASCII value of character 0 is 48
ASCII value of character 1 is 49
ASCII value of character 2 is 50
ASCII value of character 3 is 51
ASCII value of character 4 is 52
ASCII value of character 5 is 53
ASCII value of character 6 is 54
ASCII value of character 7 is 55
ASCII value of character 8 is 56
ASCII value of character 9 is 57
ASCII value of character : is 58
ASCII value of character ; is 59
ASCII value of character < is 60
ASCII value of character = is 61
ASCII value of character > is 62
ASCII value of character ? is 63
ASCII value of character @ is 64
ASCII value of character A is 65
ASCII value of character B is 66
ASCII value of character C is 67
ASCII value of character D is 68
ASCII value of character E is 69
ASCII value of character F is 70
ASCII value of character G is 71
ASCII value of character H is 72
ASCII value of character I is 73
ASCII value of character J is 74
ASCII value of character K is 75
ASCII value of character L is 76
ASCII value of character M is 77
ASCII value of character N is 78
ASCII value of character O is 79
ASCII value of character P is 80
ASCII value of character Q is 81
ASCII value of character R is 82
ASCII value of character S is 83
ASCII value of character T is 84
ASCII value of character U is 85
ASCII value of character V is 86
ASCII value of character W is 87
ASCII value of character X is 88
ASCII value of character Y is 89
ASCII value of character Z is 90
ASCII value of character [ is 91
ASCII value of character  is 92
ASCII value of character ] is 93
ASCII value of character ^ is 94
ASCII value of character _ is 95
ASCII value of character ` is 96
ASCII value of character a is 97
ASCII value of character b is 98
ASCII value of character c is 99
ASCII value of character d is 100
ASCII value of character e is 101
ASCII value of character f is 102
ASCII value of character g is 103
ASCII value of character h is 104
ASCII value of character i is 105
ASCII value of character j is 106
ASCII value of character k is 107
ASCII value of character l is 108
ASCII value of character m is 109
ASCII value of character n is 110
ASCII value of character o is 111
ASCII value of character p is 112
ASCII value of character q is 113
ASCII value of character r is 114
ASCII value of character s is 115
ASCII value of character t is 116
ASCII value of character u is 117
ASCII value of character v is 118
ASCII value of character w is 119
ASCII value of character x is 120
ASCII value of character y is 121
ASCII value of character z is 122
ASCII value of character { is 123
ASCII value of character | is 124
ASCII value of character } is 125
ASCII value of character ~ is 126
ASCII value of character  is 127
ASCII value of character Ç is 128
ASCII value of character ü is 129
ASCII value of character é is 130
ASCII value of character â is 131
ASCII value of character ä is 132
ASCII value of character à is 133
ASCII value of character å is 134
ASCII value of character ç is 135
ASCII value of character ê is 136
ASCII value of character ë is 137
ASCII value of character è is 138
ASCII value of character ï is 139
ASCII value of character î is 140
ASCII value of character ì is 141
ASCII value of character Ä is 142
ASCII value of character Å is 143
ASCII value of character É is 144
ASCII value of character æ is 145
ASCII value of character Æ is 146
ASCII value of character ô is 147
ASCII value of character ö is 148
ASCII value of character ò is 149
ASCII value of character û is 150
ASCII value of character ù is 151
ASCII value of character ÿ is 152
ASCII value of character Ö is 153
ASCII value of character Ü is 154
ASCII value of character ¢ is 155
ASCII value of character £ is 156
ASCII value of character ¥ is 157
ASCII value of character ₧ is 158
ASCII value of character ƒ is 159
ASCII value of character á is 160
ASCII value of character í is 161
ASCII value of character ó is 162
ASCII value of character ú is 163
ASCII value of character ñ is 164
ASCII value of character Ñ is 165
ASCII value of character ª is 166
ASCII value of character º is 167
ASCII value of character ¿ is 168
ASCII value of character ⌐ is 169
ASCII value of character ¬ is 170
ASCII value of character ½ is 171
ASCII value of character ¼ is 172
ASCII value of character ¡ is 173
ASCII value of character « is 174
ASCII value of character » is 175
ASCII value of character ░ is 176
ASCII value of character ▒ is 177
ASCII value of character ▓ is 178
ASCII value of character │ is 179
ASCII value of character ┤ is 180
ASCII value of character ╡ is 181
ASCII value of character ╢ is 182
ASCII value of character ╖ is 183
ASCII value of character ╕ is 184
ASCII value of character ╣ is 185
ASCII value of character ║ is 186
ASCII value of character ╗ is 187
ASCII value of character ╝ is 188
ASCII value of character ╜ is 189
ASCII value of character ╛ is 190
ASCII value of character ┐ is 191
ASCII value of character └ is 192
ASCII value of character ┴ is 193
ASCII value of character ┬ is 194
ASCII value of character ├ is 195
ASCII value of character ─ is 196
ASCII value of character ┼ is 197
ASCII value of character ╞ is 198
ASCII value of character ╟ is 199
ASCII value of character ╚ is 200
ASCII value of character ╔ is 201
ASCII value of character ╩ is 202
ASCII value of character ╦ is 203
ASCII value of character ╠ is 204
ASCII value of character ═ is 205
ASCII value of character ╬ is 206
ASCII value of character ╧ is 207
ASCII value of character ╨ is 208
ASCII value of character ╤ is 209
ASCII value of character ╥ is 210
ASCII value of character ╙ is 211
ASCII value of character ╘ is 212
ASCII value of character ╒ is 213
ASCII value of character ╓ is 214
ASCII value of character ╫ is 215
ASCII value of character ╪ is 216
ASCII value of character ┘ is 217
ASCII value of character ┌ is 218
ASCII value of character █ is 219
ASCII value of character ▄ is 220
ASCII value of character ▌ is 221
ASCII value of character ▐ is 222
ASCII value of character ▀ is 223
ASCII value of character α is 224
ASCII value of character ß is 225
ASCII value of character Γ is 226
ASCII value of character π is 227
ASCII value of character Σ is 228
ASCII value of character σ is 229
ASCII value of character µ is 230
ASCII value of character τ is 231
ASCII value of character Φ is 232
ASCII value of character Θ is 233
ASCII value of character Ω is 234
ASCII value of character δ is 235
ASCII value of character ∞ is 236
ASCII value of character φ is 237
ASCII value of character ε is 238
ASCII value of character ∩ is 239
ASCII value of character ≡ is 240
ASCII value of character ± is 241
ASCII value of character ≥ is 242
ASCII value of character ≤ is 243
ASCII value of character ⌠ is 244
ASCII value of character ⌡ is 245
ASCII value of character ÷ is 246
ASCII value of character ≈ is 247
ASCII value of character ° is 248
ASCII value of character ∙ is 249
ASCII value of character · is 250
ASCII value of character √ is 251
ASCII value of character ⁿ is 252
ASCII value of character ² is 253
ASCII value of character ■ is 254
ASCII value of character   is 255
*/